apiVersion: external-secrets.io/v1

kind: ExternalSecret

metadata:
  name: shopping-app-secret
  namespace: shopping

spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager

  target:
    name: shopping-app-secret
    creationPolicy: Owner

  data:
    - secretKey: DB_USER
      remoteRef:
        key: devops-levelup/staging/shopping-app
        property: DB_USER

    - secretKey: DB_PASSWORD
      remoteRef:
        key: devops-levelup/staging/shopping-app
        property: DB_PASSWORD
