{{- if .Values.ingress.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ include "shopping-app.fullname" . }}

  labels:
    {{- include "shopping-app.labels" . | nindent 4 }}

spec:
  ingressClassName: {{ .Values.ingress.className }}

  rules:
    - host: {{ .Values.ingress.host }}

      http:
        paths:
          - path: /

            pathType: Prefix

            backend:
              service:
                name: {{ include "shopping-app.fullname" . }}

                port:
                  number: {{ .Values.service.port }}

{{- end }}
