apiVersion: v1
kind: Service

metadata:
  name: postgres

  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}

  ports:
    - name: postgres
      port: {{ .Values.postgresql.service.port }}
      targetPort: postgres
      protocol: TCP
