apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres

  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}

spec:
  replicas: 1

  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/instance: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/instance: {{ .Release.Name }}

    spec:
      containers:
        - name: postgres

          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"

          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}

          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP

          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "shopping-app.fullname" . }}-config
                  key: DB_NAME

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: shopping-app-secret
                  key: DB_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shopping-app-secret
                  key: DB_PASSWORD

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

          resources:
            {{- toYaml .Values.postgresql.resources | nindent 12 }}

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
