---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shopping-app-secret
  namespace: shopping
spec:
  encryptedData:
    DB_PASSWORD: AgC7N+xfA7ldv8bcQRPrhh2vLrs4ubXfjVmYqKngO3wnF+k+vgv2gVK7YkS0AXNhbc3+iHlCGWVme6zBaSbtVF+YELqCPDidYSWbuVGfpqlVdotk5l7HtdOqEBtybSRMTwRZeIPkx5U5kfA6nPH/YSN1WOqeewf4dKu0HnKcoJwX6ssjlnn400zS6cCoPRqe2RVLrElj0O/MNgxZy/jFYpB1p1qJ6wG6Cly7ZCIE2hH+RKJ5PnuAUlKucqF3Bqv9tbsI8W75BzoYo4OqkFgRGrLR+6AdIrZaIC3B2GV8X8cFcdPI1BAuNgnefUjxNypVazM7q1YQMZ2Hqe95Z2IbIovuDGPH1QXelr7snhSkQEuRwnhfyYVUQ9h6f+39P0CZ9dvTzvAtX/YMTdV67NsTZFYsf4IpMeqazBOTgKJSsp7Va1meUeTDK7K6YlGfguASn32oqPfwEDuj3F4OTZ9Hj+YxL6/7cnNxoHkVtVxcpcopgmslfbvjMUg0VsmaKyPML6vIPKctVSsxCHN2Tx0LIhbafM2zfAbdFmANXz8kLtYHXqcFanBPllovX3WoxO1eSw4jwz1zAOWedvGpz36W9BX6ltB0j4Ln/TzZi3s59cdBE7Uh3YhxTAF7qyzuG3d5pRvl0gV6fDqlwDGLQBHDht4+fniZ/hKDMH6jr+m2KF3tiSAdQzI8NB5DXTN/Y9Zg9WipfJvy4saW8mRhdg==
    DB_USER: AgAXlvUgj1meNqPYxshg8vxbC4ty2enc9xky8TG8Aff9tMJ0C1MR3Nm6ZAEKpjPQcmUkJ4lLO+NxFcvqnjX76KUVl2XRj75Xzzp5IVEAYUmevISoEbIE+x9vOxwNBmnaTMIYS0JzPs9C+mMJUuisthQI2BxMVU593vCb/m3fq+rtWDW+ubDAKJQUWjf6ckHbHnSVmA5g2JXNP3cF9ovuo9wbSYSkFTUl2iLE1bsux392Ef+qOiLDE+etyFpVRE/pqc/1otKTZzCcj7sFr7UgJSd/kLmFRJU+Fz2K7lBI9g52hlVK6EHducocMddYTKVWF987P14nDTpOOq7QFY52K+gV+IUzy6aSJDkrRiCpXs8O51n5sUUoozqs1FC1u4Rz73WogkD6EBRBcHn+lLGAmLqeOVzLu1rysG9/ou6vd/AFIjQHM+FvFTCGH5PMkAITb1NdGeZS45Jk53rnkFPfQ2R5sJiYoYU/IXgKRuogfz9nOGRflcZ6lm0ii4LppL17IHiSUvWrba/9L36ewhWd6f7VdvHD2ppScB5rId8DfG/HDJq2SdXw7BELDmzLxA2x+fxqtus30bsvuGYmTuTCnY2mDyciIUhnNDLhNt6pQspu/q/+8pYuK7LiFNmjAFGWqJvlZjgFk5A0HRlMG989Y1JFMa0+nGpgT3wekeZtlY6GOB2onF97YglEeorqEDwJ2R4wsNVAKa7u8w==
  template:
    metadata:
      creationTimestamp: null
      name: shopping-app-secret
      namespace: shopping
