---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shopping-app-secret
  namespace: shopping
spec:
  encryptedData:
    DB_PASSWORD: AgAU7AS/jDaNILqg4DeAp2pvFBBLygCwABNC79schjBUQnHY/oQvgBL1Hxru/fFH7roHB70OQWuiF8slK+pF6zRBohs/wvad7GmvnA6C74yiEpuqUrHkOPF5B2tIlIPbiLmn8VTyR3Pi0NYiY6GsLXE1WhGQemGlB61EoSTi53ixce1eJPUq8wgxB+YVHuh5vSWCuhg8rdDb1mq7nr5HgMByJKMuK0YfgfgHOzKi+OFrUZOeIv/XjkmH7+WIF7PvXH0xfFZJMH+W+dZhuZ2Vz7gZsHToQjq2gbf4bUahlSZlf0KPZRO7iskA1CnY7pVW1sULpeP6PQp4If0kLKEy2TU0mQsfeEpd303AvuTih01bsndJESCq37pXarRKMaVrnjpcqPXtDHegqbb5UyNDoJ+aAeaglaCGtmNdQRsBlEgwjIxvTyWs/a+7A7MsNBAXtL9PjOJKqwC6BvqcmkqYdyBSVfQC8ISik+0fjWvgj2JYYSbi3j+05IvPSoW3/hJuFumrebSBIdZoRLm9PhEhyTshnSVg/OmOyklASmctlGl5aQ6R+L5nkMSinBPdQRE7OcLhAFwxtGcwLnrfABQmwkjupkS3eu17I9UQ6MzZjOa2H4ntSw0VhNtkszRX1/5JiJxtiHXJN+H/HjrfHlGvMb6KN6Cj3E71zoOEA+vMfVe7tF00LkKXgnDaSNHIH93vOweR8oh0UMF9lQ==
    DB_USER: AgAlu4MnJX4COYEqAdwyWcqBn8+wnspbCZyzczZQPxaMnXA3a8IofNUVLFTADR0DMOWUtABOKgRexbzsov8bhUfppyefWedBRs8PPTLRVicBzJFjicjbTrOGSCl5xQcWy+l3ADG5XjGIBN7VJRd6fUZaSTX/6lwZGQu0qU1KwNV+Gf22akIzgMQq2d1DDPuvXq6TSw2yQuz9Qwp71KOKI9dxZ/LHkX16w9wGOLGHVP2DvLYsxQBOZCkyfdh0uB4EDU9U38gXykEQX4KTDgOh/Hx9vFCqYTg34q3Po4IcnAv0WA7GOfcncy3gCTlaM34x6f/1tftPLzRbAhyCllEPpOhkJMMLT4HTuadB52+c03vB9JinskuDCcGugWIJxgsu0J681DDvIHuN564RPgGGlha1LNJutC1TRAElqTjBpgXod3f9oJ5ivY0+GOTSDOCAk5VvTUn946XE8aT9dmW3AAXPmLWGQJOCfQKRYP2rF9HZmtUp5U1ibFuZ2RZIxBTXDXtK6WqMb2LDMXC+oM5xhSxRg2qhWpCw14NAaQqOIQeWx6XGhIGC3nSueUeNWEE5HT5N4NvDM6z8lYcL76vIcalVKoI/RMEiSUKNRyvJmmCcnH1yGTRdzaPqdUtswmqEJmfx/KweQHrpUjzHOGf38LGx+cABle38A9yLVq8oxVHgRJhTjJ2b3Ewx7zDegK5Ohs5dgb3w+R5Ziw==
  template:
    metadata:
      creationTimestamp: null
      name: shopping-app-secret
      namespace: shopping
    type: Opaque
