---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shopping-app-secret
  namespace: shopping
spec:
  encryptedData:
    DB_PASSWORD: AgDcSdq4Tc45paHmCibnjGL3slk7cZGNX5z764+yeDNDCNieKHsrfJC1yHlzwwr8FwP0Fe/cwiSNsjyOs6nmYCze1UwEPiDfGtkRuEzow1yxRUwCibgZVz1K7Jv/CDkCFhHhS78suB/mr465gEQcOO+jpKl1GyPrTRmMulB+g0WeT0KwRsY3ETref4SuTwahRDrWRIGjESzfdPJLm1EKgX7403y1250TiX34GtHL9WpCyTVMu0JJRlDzSxjNi73sW5t+vMc5eYnA8CZu7MLWWk2VGPn7N4YRBDREDf3rY5JoHr9fizUc9lXX/BuALaFy+K3dzXl08Zl8XTrmAop3rJ6GscdF8W4fjDNQNSOL+uIF7XpS3jxMF+F6StaBv8DQ+CetNfQxCzltw5Ogwt1VtCQym9UPBqdPkvcBCVPiJSeLZWF8hwKfnRSKLEphClIiTc9+hazlzafZ+Q8S++CBauyehWd3wJWbtlW0FZD1KwoDiq0blnuy7rLTzS2xVlfU4BhtAkf9OBWjJGQalOoiousaba1luoY5lp7uPa/0bKV3zPzX7JpqyREk+XNUn1/WZPgFeLCjvQx5CoA/32FHJhBc7J4wGRQlZ08essb3rO+RJCE+gkUJ4B6kE2e0cE/n2keX71ycdv70uIdx0iN+ioOIcjMK5vZ+Lz/hvNlBYvvtMQIeECvQAp5028GGyr3ezjQjgyEVG9r5QQ==
    DB_USER: AgBH9fi41qTx8NMjjj2eh0hveyiMkkBwXgZt9EZ+xTqs0j36ADmL2p3qepCZ4BF2we77QOtAxCK7AuHrgk1f2rjKOmPUPjJziv456XiFUGdAJwy1f8KlH0hSXORpKpsAwCs5FinaMRegXdERsu97PNy6XJDMcGZT0ti4up+phQ2CqOwMQj89qDt2/WDcugwRQGqimv+fa2FuhKlGMDbL7o1hDbN0kzzNgPCrfDDvVdRofmqpmeUJh4IH1PvOnHtnjyhIyDTE+SKgg7uucEbEZial3+fZeHqzVkXUGr5MTKJqmiZI4joeP0La8ITv09c0xthgmuu1kweGWdz5l64d0tYaqTZRynsdKkx/hl7Pvk20DG3VsSEg1N/5ocJmf78sra2hI+WHB3VSmzVKMI7Pf6rCmy6gIjYoNZFTrxncR8+iBJoIsLy/ge0ZFJJMl4/L5k3xHTN6r3dLAacTqnmtZGsJYkWvi1Dh/TscFbQ60bbsw3oSJr57vw97tQemwy7g//aVjbWvK+svQt5VhWE9V6/60NpsdV3muRs3Zf8fUmp6ezGUs31kCmJzOzduVSaJACiaSH006mWNsKi02Ejqb3fpftLx6fGSYQa6OpFSELrYhCl9PAsVXXgUMsYKlVCsxumhgZm4TrgNVUsK7AzRK1vNI4xooBsaj+hBLjPWnO/FmF9HAmwA2vp/xisG8RVA9bYsuBV47SkdWA==
  template:
    metadata:
      creationTimestamp: null
      name: shopping-app-secret
      namespace: shopping
    type: Opaque
