apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: keycloak-postgres-data

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: {{ .Values.keycloakx.postgresql.persistence.storageClass }}

  resources:
    requests:
      storage: {{ .Values.keycloakx.postgresql.persistence.size }}
