apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
  namespace: {{ .Release.Namespace }}
data:
  devops-lvlup-realm.json: |
    {
      "realm": "devops-lvlup",
      "enabled": true,
      "roles": {
        "realm": [
          {
            "name": "reader"
          },
          {
            "name": "writer"
          },
          {
            "name": "admin"
          }
        ]
      },
      "clients": [
        {
          "clientId": "shopping-app",
          "name": "shopping-app",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": true,
          "directAccessGrantsEnabled": true,
          "standardFlowEnabled": true,
          "attributes": {
            "pkce.code.challenge.method": "S256"
          },
          "redirectUris": [
            "https://app.cdevops-levelup.ro/*"
          ],
          "webOrigins": [
            "https://app.cdevops-levelup.ro"
          ],
          "protocolMappers": [
            {
              "name": "shopping-app-audience",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-audience-mapper",
              "consentRequired": false,
              "config": {
                "included.client.audience": "shopping-app",
                "id.token.claim": "false",
                "access.token.claim": "true"
              }
            }
          ]
        }
      ]
    }
