---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-admin
  namespace: keycloak
spec:
  encryptedData:
    KC_BOOTSTRAP_ADMIN_PASSWORD: AgCJfK4BJ2nlULrji6iZSzp0XnhInbsGTHWxP9eK6e/gMXHx7Dn/ilnjlTdPCqGfmM5HpjFltVBixFIGZWYKXWTKH2DIxOx/50K8zTUYx3aqQThIcooNVhwNAVyG7s9oYBf9XAGGI9YwGs5vUCqT6jqHIby3SF4+VflTWQQ7zI39ifsxS096dAM9BQRREwpY1KxJ1tD4a2N4qROoJMk3IMf2JBHK0Dv7OdRFiglh9aIaeBfkt/vufRgmkMPc8vEwVT9R3WhDKLHAP08/KG/XBD2cfcfVVmsqoJaWe9a2xCdrVCyAEaHbokZ+KywcA2g48SvTjGtlf3hl/UW9xO4ImGboMFRhwcjYUa9RrqkrNWHd06qxqwslQPABYdyP4akgkFRaA93oExIQlCipUhM1GP6+hUOFSOGaXk64jruzigQzUjgjS3OK+r2UX5dsbEPxwklpMCTORmy+oI3qltGtndaQ6vbuBPhG1Ki2mTKq16QeAz8g+ccokYdS7135T6HLRbnYS8pAhAaACjbfjKzGzk0J+kObl3pfWSjvb/c8oQz5gXsCPlTpHucyMag0xgNGeG8QJpljjHQZ2nld4ykQGp/h59C3dVzQdtbYNWNbSgFREagP+2eDdF6Y4307Zg08fumk3Zr8v1Qo36NqZAPaCqYVx+BqF79Pw40mIBTnGTh8EfjT7o82iIyaZ3KquPF+9JBh3rafEi4XsAWa27V4yMre+SOSZILn
    KC_BOOTSTRAP_ADMIN_USERNAME: AgDlY9d6x6cSw30cFuBEldp8aH+gnmpXhE6svD8bpoFc8U8SW2JUJQn5UyYf4QmicIEw/WwHRLe8UQxPB96833mNKXgwAoT6scLHZ/ZlPRgC8f877uAaHZo7zVQ69ZEWaSUBsiKvyZs4T6IOdFJanHzCD/y4KZia//T1haNe5w7FtOd/VeBcLV2cFB7wpHnSEXLZYKxX/ZL1BNEI5pFfNax0ztVGfVBYaagbYxx9vZls00Xl4WMBwrq/3p21JvFlPljISKXZi+ViRF7fdK7apnG8gz4BZo3BcDuWPI2wfS3E+UYS+pw9vBOkbp+n/nWDV3cN39Jhi3kbUBEweanGTZhY25fGuo3y+UZntY6pJwLxJoq1T2AJtk/AiyMJFIB6Lu5lTPdtX1vUQuxqzRuBK51fwbwXgZ7qraXxHNPUvfFATi3Va3Rbnh5ko0iJhac9+fREVSRY+8bxx+onkgxnV9BIarH7YYXY0JBhnd8iCjlYb8fWkITcBdTaTVyq+m9uiTx0KJx5bEvO9CPvAuN6JOkNfKaY7rQEQTPH2BRPyx7cFgj87yqom74Vqd0x0I56DavkXU5N72ALXpiJZTvtgBD304pXpW71d+n39+7oG51c25nSxUDsRgCbHC6EbtUOt/LHuxvJ42eDhlBaZKvRZOigkIyS4uiVy35Kzj3m+E5u/UhsJa3jGOBHJkx3EFFOFtMxnErAZQ==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-admin
      namespace: keycloak
    type: Opaque
