jaeger:
  provisionDataStore:
    cassandra: false

  storage:
    type: memory

  allInOne:
    enabled: true

    service:
      otlp:
        grpc:
          name: otlp-grpc
          port: 4317
        http:
          name: otlp-http
          port: 4318

  collector:
    enabled: false

  query:
    enabled: false

  agent:
    enabled: false

  ingester:
    enabled: false
