jaeger:
  provisionDataStore:
    cassandra: false

  storage:
    type: memory

  allInOne:
    enabled: true

    extraEnv:
      - name: COLLECTOR_OTLP_ENABLED
        value: "true"

  collector:
    enabled: true

    service:
      otlp:
        grpc: {}
        http: {}

  query:
    enabled: true

  agent:
    enabled: false

  ingester:
    enabled: false
