jaeger:
  provisionDataStore:
    cassandra: false

  storage:
    type: memory

  allInOne:
    enabled: true

    extraEnv:
      - name: COLLECTOR_OTLP_ENABLED
        value: "true"

  collector:
    enabled: true

    service:
      otlp:
        grpc:
          name: otlp-grpc
          port: 4317

        http:
          name: otlp-http
          port: 4318

  query:
    enabled: true

  agent:
    enabled: false

  ingester:
    enabled: false
