replicaCount: 2

image:
  repository: cristiancosmin/shopping-app 
  tag: "f542e77"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: nginx
  host: app.local

  tls:
    enabled: true
    secretName: shopping-app-tls
    clusterIssuer: selfsigned-clusterissuer

database:
  host: postgres
  port: 5432
  name: shopping

postgresql:
  image:
    repository: postgres
    tag: "16"
    pullPolicy: IfNotPresent

  service:
    port: 5432

  persistence:
    enabled: true
    size: 1Gi
resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50


keycloak:
  issuer: "https://auth.local/realms/devops-lvlup"
  jwksUrl: >-
    http://keycloak-keycloakx-http.keycloak.svc.cluster.local/realms/devops-lvlup/protocol/openid-connect/certs
  audience: "shopping-app"

otel:
  exporterOtlpEndpoint: "http://opentelemetry-opentelemetry-collector.observability.svc.cluster.local:4318"
  serviceName: "shopping-app"
  resourceAttributes: "deployment.environment=local"
