ingress:
  host: app.cdevops-levelup.ro

  tls:
    enabled: true
    secretName: shopping-app-tls
    clusterIssuer: selfsigned-clusterissuer

postgresql:
  persistence:
    storageClass: gp2

otel:
  resourceAttributes: "deployment.environment=staging"

keycloak:
  issuer: "https://auth.cdevops-levelup.ro/realms/devops-lvlup"
