ingress:
  host: app.local

  tls:
    enabled: true
    secretName: shopping-app-tls
    clusterIssuer: selfsigned-clusterissuer

postgresql:
  persistence:
    storageClass: local-path

otel:
  resourceAttributes: "deployment.environment=local"
