loki-stack:
  promtail:
    enabled: true

  grafana:
    enabled: true

    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        searchNamespace: ALL

  loki:
    enabled: true
